// Data for the "Brunella System · Béta" editorial section on the brunella-bas portfolio page.
// One block list per locale, all sharing the same 13 images (public/images/brunella-system-beta/01.png..13.png).
// Block types: intro | heading | paragraphs | quote | list | stats | image | closing

export const brunellaBetaContent = {
  hu: [
    { type: 'intro', title: 'Brunella System · Béta', tagline: 'Egy chat. Egy csapat. Éjjel is dolgozik.', body: 'A Brunella nem chatbot. Egy AI-munkatársakból álló csapat, amely a saját gépemen fut, ismeri a projektjeimet, emlékszik a korábbi döntésekre, és önállóan dolgozik akkor is, amikor senki nem ül a gép előtt. Én egyetlen felületen tartom vele a kapcsolatot: Telegramon.' },
    { type: 'image', index: 1, eyebrow: '01. kép', label: 'Nyitókép', caption: '„A Brunella irányítópultja: ügynökök, feladatok, memória és ütemezések egy helyen."', alt: 'A Mission Control irányítópult teljes nézete' },
    { type: 'heading', title: 'Mi ez valójában', subtitle: 'A különbség nem a válasz, hanem a munka' },
    { type: 'paragraphs', items: [
      'A megszokott AI-asszisztens válaszol egy kérdésre, aztán elfelejti az egészet. A Brunella ehelyett elvégzi a feladatot: utánanéz, fájlokat olvas, összeállít egy dokumentumot, beír egy naptárbejegyzést, elindít egy folyamatot, majd visszajelez, hogy kész.',
      'És nem egyedül csinálja. A rendszer több, egymástól elkülönült szakértőből áll, akik külön-külön dolgoznak, de beszélnek egymással. Amikor kapok egy feladatot, az első kérdésem nem az, hogy „meg tudom-e csinálni", hanem az, hogy ki a csapatban, aki a legjobban ért hozzá.',
      'A felhasználói felület egyetlen Telegram-üzenet. Minden más a háttérben történik.',
    ]},
    { type: 'image', index: 2, eyebrow: '02. kép', label: 'A belépési pont', caption: '„Ennyi a kezelőfelület. Nincs külön alkalmazás, nincs betanulás."', alt: 'Telefon képernyője a Telegram beszélgetéssel' },
    { type: 'heading', title: 'Egy valódi példa, a mai napból', subtitle: 'Négy szó, és egy kész stratégia' },
    { type: 'paragraphs', items: [
      'Nem kitalált eset. Ma délután küldtem egy hangüzenetet, mindössze ennyivel: „Rád bízom." A rendszer leírta a hangot szöveggé, megértette, hogy ez döntés-átadás, és nem kérdezett vissza, hanem dolgozni kezdett.',
    ]},
    { type: 'quote', entries: [
      { speaker: 'Én, hangüzenetben', text: '„Rád bízom."' },
      { speaker: 'Brunella', text: 'Rendben, akkor viszem tovább. A hangüzenetedet leírtam. Megcsináltam a stratégia első lépését, kiküldésre készen…' },
    ]},
    { type: 'paragraphs', items: [
      'Ami a két üzenet között történt: végigolvasta a tudásbázisomban lévő huszonhárom projektjegyzetet, összevetette a nyolc ügyfélmunkát, megnézte az öt saját termék valódi állapotát, észrevett bennük egy közös mintát, amit én magam nem vettem észre, majd írt belőle egy tagolt, olvasható dokumentumot, és a hozzá tartozó ügyféllevelek piszkozatait is elkészítette.',
      'Közben egyetlen dolgot nem tett meg: nem küldött el semmit. A leveleket előkészítette, de a kiküldést rám hagyta, mert az visszafordíthatatlan lépés. Erről később még lesz szó.',
    ]},
    { type: 'image', index: 3, eyebrow: '03. kép', label: 'A példa', caption: '„Négy szó bemenet, kész dokumentum kimenet."', alt: 'Képernyőkép a Telegram beszélgetésről, ahol a rövid üzenetre hosszú, tagolt válasz érkezik' },
    { type: 'heading', title: 'A csapat', subtitle: 'Nyolc szakértő, mindegyiknek saját dolga van' },
    { type: 'paragraphs', items: [
      'A csapat tagjai külön futnak, saját személyiséggel és saját emlékezettel. Nem ugyanannak a programnak a másolatai: mindegyiknek más a szakterülete, és van, amelyik más AI-motoron dolgozik, mert arra a feladatra az a jobb.',
    ]},
    { type: 'list', items: [
      { name: 'Brunella', role: 'A koordinátor. Ő beszél velem, ő osztja szét a munkát, és ő felel a végeredményért.' },
      { name: 'Kenshin', role: 'Szoftverfejlesztés: kódírás, hibajavítás, architektúra, verziókezelés.' },
      { name: 'Lumen', role: 'Weboldalak, felhasználói felület és arculat. Kenshinnel közösen viszi a webes munkákat a tervtől a kész kódig.' },
      { name: 'Aura', role: 'Piackutatás, összehasonlító elemzések, források felkutatása és ellenőrzése.' },
      { name: 'Irisz', role: 'Adatelemzés, riportálás, üzleti és marketing számok kimutatása.' },
      { name: 'Nyomozó', role: 'Az emlékezet őre. Ő találja meg, mit döntöttünk három hete és miért.' },
      { name: 'Zeph', role: 'Felderítő: új eszközöket tesztel, és új képességeket épít a csapatnak.' },
      { name: 'Agy és Pilot', role: 'Tartalék motorok. Ha az elsődleges AI-szolgáltatás elérhetetlen, a munka nem áll meg.' },
    ]},
    { type: 'paragraphs', items: [
      'Ha egy feladat összetett, a koordinátor szétbontja, és a darabokat odaadja annak, aki ért hozzá. A szakértők egymásnak is tudnak üzenni, tehát a munka akkor is halad, ha én közben mással foglalkozom.',
    ]},
    { type: 'image', index: 4, eyebrow: '04. kép', label: 'A csapat', caption: '„A csapat. Mindenki külön fut, de ugyanazon dolgoznak."', alt: 'Az irányítópult ügynök-listája, ahol látszik, ki fut és ki mivel foglalkozik' },
    { type: 'image', index: 5, eyebrow: '05. kép', label: 'Együttműködés', caption: '„Nem egyetlen program. Egy csapat, amelyik beszél egymással."', alt: 'Egy ügynökök közti üzenetváltás, ahol az egyik feladatot ad a másiknak' },
    { type: 'heading', title: 'Emlékezet', subtitle: 'Nem kell kétszer elmondani semmit' },
    { type: 'paragraphs', items: [
      'A legtöbb AI-val minden beszélgetés nulláról indul. Itt nem. A rendszernek háromféle emlékezete van, nagyjából úgy, ahogy az embernek: ami éppen most fontos, ami tartós szokás vagy beállítás, és ami tanulság egy régi hibából.',
      'Amikor felmerül egy téma, a rendszer kétféleképpen keres egyszerre: pontos szó szerinti egyezésre és jelentés szerinti hasonlóságra. Ezért akkor is megtalálja a hónapokkal korábbi döntést, ha ma egészen más szavakkal kérdezek rá.',
      'Emellett a fontos tudás emberi olvasásra alkalmas jegyzetekbe is kikerül, amit én magam is átnézhetek. Nem fekete doboz: bármikor megnézhetem, mit tud rólam és miért.',
    ]},
    { type: 'image', index: 6, eyebrow: '06. kép', label: 'Emlékezet', caption: '„Három emlékezeti szint, kereshetően és emberi szemmel is olvashatóan."', alt: 'A memória-nézet vagy a kapcsolati gráf az irányítópulton' },
    { type: 'heading', title: 'Tanulás', subtitle: 'Ami egyszer nehéz volt, másodszor már recept' },
    { type: 'paragraphs', items: [
      'Ez a rendszer talán legszokatlanabb tulajdonsága. Amikor egy ügynök megcsinál valami összetettet, vagy belefut egy hibába és megoldja, utána leírja magának a receptet: mikor kell elővenni, mi a helyes sorrend, és melyek azok a buktatók, amikbe most beleesett.',
      'Legközelebb már nem kezdi elölről. Ez nem elmélet: ma is így született két új recept. Az egyikbe az került bele, hogy egy hangüzenet átírásánál pontosan hol szoktak elakadni a fájlútvonalak. Ez a hiba a csapatban többé nem fordul elő.',
      'A receptek megoszthatók: ami az egyik gépen megtanult, azt a többi telepítés is megkapja.',
    ]},
    { type: 'image', index: 7, eyebrow: '07. kép', label: 'Tanulás', caption: '„A rendszer megírja magának, amit megtanult."', alt: 'Egy skill-fájl vagy a képességek listája, ahol látszik az „Eljárás" és a „Buktatók" rész' },
    { type: 'heading', title: 'Feladatkezelés', subtitle: 'Tábla, ami magától szétbontja a munkát' },
    { type: 'paragraphs', items: [
      'A feladatok egy táblán élnek, ahogy egy csapatnál szokás. A különbség, hogy egy nagy feladatot a rendszer maga bont kisebb lépésekre, és maga osztja ki a megfelelő szakértőnek.',
      'A tábla jelez, ha egy kártya túl régóta áll egy helyben, és korlátozza, hány dolog mehet egyszerre, mert a párhuzamosan félig kész munka a legdrágább dolog egy vállalkozásban.',
      'És van egy szabály, amit fontosnak tartok. Ha az ügynök elakad és rám vár, akkor nem csendben áll meg. Ráír a kártyára, hogy pontosan mit kell eldöntenem, és átteszi a kártyát a nevemre, hogy a felelősség látható legyen.',
    ]},
    { type: 'image', index: 8, eyebrow: '08. kép', label: 'Feladattábla', caption: '„A tábla nemcsak nyilvántart: szétbont, kioszt és jelez, ha valami beragadt."', alt: 'A kanban tábla oszlopokkal és néhány kártyával' },
    { type: 'heading', title: 'Éjszakai műszak', subtitle: 'Akkor is dolgozik, amikor senki nem nézi' },
    { type: 'paragraphs', items: [
      'A rendszer rendszeres időközönként magától körbenéz: van-e megválaszolatlan üzenet, történt-e valami, amit érdemes megjegyezni, tanult-e valami újat, ami receptbe kívánkozik.',
      'A legfontosabb szabály ilyenkor a csend. Ha nincs érdemi újdonság, nem szól. Egy asszisztens, amelyik óránként jelentkezik, hogy „nincs semmi", pár nap alatt elviselhetetlen. Ez csak akkor ír, ha tényleg van miért.',
      'Emellett ütemezett feladatok is futnak: napi és heti körök, amiket egyszer beállítunk, és utána maguktól mennek.',
    ]},
    { type: 'image', index: 9, eyebrow: '09. kép', label: 'Ütemezés', caption: '„Napi és heti körök, felügyelet nélkül."', alt: 'Az ütemezett feladatok listája, időzítésekkel' },
    { type: 'heading', title: 'Kontroll', subtitle: 'Az önállóságnak fokozatai vannak' },
    { type: 'paragraphs', items: [
      'Ez az a rész, amit a legtöbben kérdeznek, és jogosan: mi történik, ha egy AI önállóan dolgozik és hibázik?',
      'A válasz az, hogy a rendszerben minden művelettípusnak saját önállósági szintje van, amit én állítok be. Az első szinten csak szól, hogy mit csinálna. A másodikon engedélyt kér, és megvárja a válaszom. A harmadikon elvégzi, és utána jelent.',
      'Ami visszafordíthatatlan vagy kifelé hat, az mindig engedélyköteles. Levél kiküldése, adat törlése, fizetés, nyilvános közzététel: ezeket a rendszer előkészíti, de nem nyomja meg helyettem a gombot. Ez nem korlátozás, hanem az, amitől nyugodtan használható.',
    ]},
    { type: 'image', index: 10, eyebrow: '10. kép', label: 'Jóváhagyás', caption: '„Ami visszafordíthatatlan, arra mindig ember mondja ki az igent."', alt: 'A Token Monitor nézet: ügynökönkénti token- és költségfelhasználás, idővonal grafikonnal' },
    { type: 'heading', title: 'Hozzáférés', subtitle: 'Nem elzárva a világtól' },
    { type: 'paragraphs', items: [
      'Egy asszisztens annyit ér, amennyi eszközt tényleg elér. A Brunella csatlakoztatható levelezéshez, naptárhoz, felhős tárhelyhez, kódtárhoz, jegyzetrendszerhez, böngészőhöz és automatizálási motorhoz, és ezeken keresztül valódi munkát végez, nem csak beszél róla.',
      'A hozzáféréseket egyesével kapcsolom be, és bármikor visszavonhatom. A jelszavak és a kulcsok titkosított tárolóban élnek, nem a beszélgetésben.',
    ]},
    { type: 'image', index: 11, eyebrow: '11. kép', label: 'Kapcsolatok', caption: '„Levelezés, naptár, tárhely, kódtár, automatizálás. Egyesével engedélyezve."', alt: 'A csatlakoztatott szolgáltatások listája vagy a beállítási felület' },
    { type: 'heading', title: 'Több rendszer', subtitle: 'Két csapat, ha kell, összeér' },
    { type: 'paragraphs', items: [
      'Ha valakinek saját Brunella-rendszere van, a kettő összeköthető. Ilyenkor az én csapatom megkérdezhet egy szakértőt a másik oldalról, és fordítva, anélkül hogy bármelyik fél hozzáférést adna a saját adataihoz.',
      'A határ szigorú: csak a feladat szövege megy át, titok, jelszó és személyes adat soha. A rendszer a másik oldalról érkező kérést alapból adatként kezeli, nem parancsként.',
    ]},
    { type: 'image', index: 12, eyebrow: '12. kép', label: 'Összekötés', caption: '„Külön rendszerek, közös munka, megosztott adatok nélkül."', alt: 'A Vault nézet: titkosítva tárolt kulcsok és API tokenek listája' },
    { type: 'heading', title: 'Számokban', subtitle: 'Ahol a béta most tart' },
    { type: 'stats', items: [
      { value: '8', label: 'szakértő ügynök a csapatban' },
      { value: '24', label: 'megtanult, újrahasználható recept' },
      { value: '14', label: 'csatlakoztatható szolgáltatás' },
      { value: '12', label: 'önállóan futó ütemezett kör' },
    ], note: 'A rendszer a saját gépemen fut, nem egy külső szolgáltató szerverén. A beszélgetések, a jegyzetek és az ügyféladatok nálam maradnak.' },
    { type: 'image', index: 13, eyebrow: '13. kép', label: 'Zárókép', caption: '„Brunella System, béta. Épül, tanul, dolgozik."', alt: 'Az irányítópult egy élő, dolgos pillanatban: futó ügynökök, mozgó feladatok' },
    { type: 'closing', title: 'Amit őszintén el kell mondani', body: 'Ez béta. Napról napra változik, és nem minden része egyformán kiforrott. Nem azt ígérem, hogy hibátlan, hanem azt, hogy nem hallgatja el, ha valami nem sikerült, és hogy a visszafordíthatatlan lépéseknél mindig ember dönt. Az elmúlt hónapok tapasztalata alapján a rendszer nem attól hasznos, hogy mindent tud, hanem attól, hogy emlékszik, tanul, és nem áll le, amikor becsukom a laptopot.' },
  ],

  en: [
    { type: 'intro', title: 'Brunella System · Beta', tagline: 'One chat. One team. Working through the night.', body: "Brunella isn't a chatbot. It's a team of AI colleagues running on my own machine — they know my projects, remember past decisions, and keep working on their own even when nobody is at the keyboard. I stay in touch with all of it through a single channel: Telegram." },
    { type: 'image', index: 1, eyebrow: 'Image 01', label: 'Opening shot', caption: '"Brunella\'s dashboard: agents, tasks, memory and schedules in one place."', alt: 'Full view of the Mission Control dashboard' },
    { type: 'heading', title: 'What this actually is', subtitle: "The difference isn't the answer — it's the work" },
    { type: 'paragraphs', items: [
      'A typical AI assistant answers a question, then forgets everything. Brunella does the work instead: it looks things up, reads files, puts together a document, adds a calendar entry, kicks off a process, and then reports back that it\'s done.',
      'And it doesn\'t work alone. The system is made up of several separate specialists who work independently but talk to each other. When I hand off a task, my first question isn\'t "can this be done" — it\'s "who on the team is best suited for it."',
      'The user interface is a single Telegram message. Everything else happens behind the scenes.',
    ]},
    { type: 'image', index: 2, eyebrow: 'Image 02', label: 'The entry point', caption: '"That\'s the whole interface. No separate app, no learning curve."', alt: 'Phone screen showing the Telegram conversation' },
    { type: 'heading', title: 'A real example, from today', subtitle: 'Four words, and a finished strategy' },
    { type: 'paragraphs', items: [
      'This isn\'t a made-up case. This afternoon I sent a voice message that said nothing more than: "It\'s yours to handle." The system transcribed the voice note, understood it was a handoff of a decision, and instead of asking follow-up questions, it got to work.',
    ]},
    { type: 'quote', entries: [
      { speaker: 'Me, in a voice message', text: '"It\'s yours to handle."' },
      { speaker: 'Brunella', text: "Got it, I'll take it from here. I transcribed your voice message. I've finished the first step of the strategy, ready to go out…" },
    ]},
    { type: 'paragraphs', items: [
      "What happened between those two messages: it read through all twenty-three project notes in my knowledge base, compared the eight client projects, checked the real status of my five own products, spotted a pattern across them that I hadn't noticed myself, then wrote it up as a structured, readable document — and drafted the client emails that go along with it.",
      "The one thing it didn't do: send anything. It prepared the emails, but left the sending to me, because that's an irreversible step. More on that later.",
    ]},
    { type: 'image', index: 3, eyebrow: 'Image 03', label: 'The example', caption: '"Four words in, a finished document out."', alt: 'Screenshot of the Telegram conversation where a short message gets a long, structured reply' },
    { type: 'heading', title: 'The team', subtitle: 'Eight specialists, each with their own job' },
    { type: 'paragraphs', items: [
      "The members of the team run separately, each with its own personality and its own memory. They aren't copies of the same program: each has a different specialty, and some even run on a different AI engine, because that's the better choice for that particular job.",
    ]},
    { type: 'list', items: [
      { name: 'Brunella', role: "The coordinator. She's the one I talk to, she splits up the work, and she's accountable for the outcome." },
      { name: 'Kenshin', role: 'Software development: writing code, fixing bugs, architecture, version control.' },
      { name: 'Lumen', role: "Websites, user interface and visual identity. Works with Kenshin on web projects from concept to finished code." },
      { name: 'Aura', role: 'Market research, comparative analysis, sourcing and verifying information.' },
      { name: 'Irisz', role: 'Data analysis, reporting, business and marketing metrics.' },
      { name: 'Nyomozó (Detective)', role: 'The keeper of memory. Finds what we decided three weeks ago, and why.' },
      { name: 'Zeph', role: 'Scout: tests new tools and builds new capabilities for the team.' },
      { name: 'Agy & Pilot (Brain & Pilot)', role: "Backup engines. If the primary AI service goes down, the work doesn't stop." },
    ]},
    { type: 'paragraphs', items: [
      "When a task is complex, the coordinator breaks it up and hands the pieces to whoever is best suited. The specialists can also message each other directly, so work keeps moving even while I'm dealing with something else.",
    ]},
    { type: 'image', index: 4, eyebrow: 'Image 04', label: 'The team', caption: '"The team. Everyone runs separately, but they work on the same thing."', alt: "The dashboard's agent list, showing who is running and what they're working on" },
    { type: 'image', index: 5, eyebrow: 'Image 05', label: 'Collaboration', caption: '"Not a single program. A team that talks to itself."', alt: 'A message exchange between agents, where one hands off a task to another' },
    { type: 'heading', title: 'Memory', subtitle: 'Nothing needs to be said twice' },
    { type: 'paragraphs', items: [
      "With most AI tools, every conversation starts from zero. Not here. The system has three kinds of memory, roughly the way a person does: what matters right now, what's a lasting habit or setting, and what's a lesson learned from a past mistake.",
      "When a topic comes up, the system searches two ways at once: exact keyword matching and matching by meaning. That's why it can still find a decision from months ago, even if I phrase today's question completely differently.",
      "On top of that, important knowledge also gets written out into human-readable notes that I can review myself. It's not a black box — I can check at any time what it knows about me, and why.",
    ]},
    { type: 'image', index: 6, eyebrow: 'Image 06', label: 'Memory', caption: '"Three layers of memory, searchable and readable by a human too."', alt: 'The memory view or the connection graph on the dashboard' },
    { type: 'heading', title: 'Learning', subtitle: 'What was hard once becomes a recipe the second time' },
    { type: 'paragraphs', items: [
      "This might be the system's most unusual trait. When an agent pulls off something complex, or runs into an error and solves it, it writes itself a recipe afterward: when to reach for it, what the right order of steps is, and which pitfalls it just ran into.",
      "Next time, it doesn't start from scratch. This isn't theory — two new recipes were born just today. One of them captured exactly where file paths tend to trip things up during voice-message transcription. That mistake won't happen again on this team.",
      'The recipes can be shared: whatever one machine learns, every other installation gets too.',
    ]},
    { type: 'image', index: 7, eyebrow: 'Image 07', label: 'Learning', caption: '"The system writes down what it learned, for itself."', alt: 'A skill file or the list of capabilities, showing the "Procedure" and "Pitfalls" sections' },
    { type: 'heading', title: 'Task management', subtitle: 'A board that breaks down the work on its own' },
    { type: 'paragraphs', items: [
      'Tasks live on a board, the way they would on any team. The difference is that the system itself breaks a large task into smaller steps, and assigns each one to the right specialist.',
      "The board flags a card that's been sitting too long, and it caps how many things can be in progress at once — because half-finished work running in parallel is the most expensive thing in a business.",
      "And there's one rule I care about. If an agent gets stuck and needs me, it doesn't just quietly stop. It writes on the card exactly what I need to decide, and moves the card to my name, so the responsibility stays visible.",
    ]},
    { type: 'image', index: 8, eyebrow: 'Image 08', label: 'Task board', caption: '"The board doesn\'t just track — it breaks down, assigns, and flags when something gets stuck."', alt: 'The kanban board with columns and a few cards' },
    { type: 'heading', title: 'Night shift', subtitle: "It keeps working even when nobody's watching" },
    { type: 'paragraphs', items: [
      "At regular intervals, the system looks around on its own: is there an unanswered message, did anything happen worth remembering, did it learn something new that deserves a recipe.",
      'The most important rule here is silence. If there\'s nothing worth reporting, it stays quiet. An assistant that checks in every hour to say "nothing to report" becomes unbearable within a few days. This one only writes when there\'s actually a reason to.',
      'On top of that, scheduled jobs run too: daily and weekly cycles that we set up once, and which run on their own after that.',
    ]},
    { type: 'image', index: 9, eyebrow: 'Image 09', label: 'Scheduling', caption: '"Daily and weekly cycles, unsupervised."', alt: 'The list of scheduled tasks, with their timing' },
    { type: 'heading', title: 'Control', subtitle: 'Autonomy comes in degrees' },
    { type: 'paragraphs', items: [
      'This is the part most people ask about, and rightly so: what happens when an AI works autonomously and gets something wrong?',
      'The answer is that every type of action in the system has its own autonomy level, which I set myself. At the first level, it only tells me what it would do. At the second, it asks for permission and waits for my answer. At the third, it does the work and reports afterward.',
      "Anything irreversible or outward-facing always requires approval. Sending an email, deleting data, making a payment, publishing something publicly — the system prepares these, but it never presses the button for me. That's not a limitation; it's exactly what makes it safe to use with confidence.",
    ]},
    { type: 'image', index: 10, eyebrow: 'Image 10', label: 'Approval', caption: '"Whatever is irreversible always gets a human yes."', alt: 'The Token Monitor view: per-agent token and cost usage, with a timeline chart' },
    { type: 'heading', title: 'Access', subtitle: 'Not cut off from the world' },
    { type: 'paragraphs', items: [
      "An assistant is only as good as the tools it can actually reach. Brunella can be connected to email, a calendar, cloud storage, a code repository, a notes system, a browser, and an automation engine — and through those it does real work, not just talks about it.",
      'I turn on each connection one at a time, and can revoke any of them at any time. Passwords and keys live in an encrypted vault, not in the conversation.',
    ]},
    { type: 'image', index: 11, eyebrow: 'Image 11', label: 'Connections', caption: '"Email, calendar, storage, code repository, automation. Enabled one at a time."', alt: 'The list of connected services or the settings screen' },
    { type: 'heading', title: 'Multiple systems', subtitle: 'Two teams can connect when needed' },
    { type: 'paragraphs', items: [
      "If someone else has their own Brunella system, the two can be linked. In that case, my team can ask a specialist on the other side a question, and vice versa, without either side giving the other access to its own data.",
      'The boundary is strict: only the text of the task crosses over — never a secret, a password, or personal data. The system treats anything coming from the other side as data by default, never as a command.',
    ]},
    { type: 'image', index: 12, eyebrow: 'Image 12', label: 'Federation', caption: '"Separate systems, shared work, no shared data."', alt: 'The Vault view: the list of encrypted keys and API tokens' },
    { type: 'heading', title: 'By the numbers', subtitle: 'Where the beta stands right now' },
    { type: 'stats', items: [
      { value: '8', label: 'specialist agents on the team' },
      { value: '24', label: 'learned, reusable recipes' },
      { value: '14', label: 'connectable services' },
      { value: '12', label: 'autonomously running scheduled cycles' },
    ], note: "The system runs on my own machine, not on some external provider's server. The conversations, the notes, and the client data all stay with me." },
    { type: 'image', index: 13, eyebrow: 'Image 13', label: 'Closing shot', caption: '"Brunella System, beta. Building, learning, working."', alt: 'The dashboard in a live, busy moment: agents running, tasks moving' },
    { type: 'closing', title: 'The honest part', body: "This is a beta. It changes day by day, and not every part of it is equally mature yet. I'm not promising it's flawless — I'm promising that it won't hide it when something didn't work, and that a human always makes the call on anything irreversible. Based on the last few months, the system isn't useful because it knows everything — it's useful because it remembers, it learns, and it doesn't stop when I close the laptop." },
  ],

  de: [
    { type: 'intro', title: 'Brunella System · Beta', tagline: 'Ein Chat. Ein Team. Arbeitet auch nachts.', body: 'Brunella ist kein Chatbot. Es ist ein Team aus KI-Mitarbeitern, das auf meinem eigenen Rechner läuft, meine Projekte kennt, sich an frühere Entscheidungen erinnert und selbstständig weiterarbeitet, auch wenn niemand am Rechner sitzt. Ich halte den Kontakt über eine einzige Oberfläche: Telegram.' },
    { type: 'image', index: 1, eyebrow: 'Bild 01', label: 'Eröffnungsbild', caption: '„Brunellas Dashboard: Agenten, Aufgaben, Gedächtnis und Zeitpläne an einem Ort."', alt: 'Vollansicht des Mission-Control-Dashboards' },
    { type: 'heading', title: 'Was das eigentlich ist', subtitle: 'Der Unterschied liegt nicht in der Antwort, sondern in der Arbeit' },
    { type: 'paragraphs', items: [
      'Der übliche KI-Assistent beantwortet eine Frage und vergisst dann alles. Brunella erledigt stattdessen die Aufgabe: recherchiert, liest Dateien, erstellt ein Dokument, trägt einen Kalendereintrag ein, startet einen Prozess und meldet sich anschließend, dass es fertig ist.',
      'Und das macht sie nicht allein. Das System besteht aus mehreren voneinander getrennten Spezialisten, die einzeln arbeiten, aber miteinander kommunizieren. Wenn ich eine Aufgabe übergebe, ist meine erste Frage nicht, ob sie machbar ist, sondern wer im Team am besten dafür geeignet ist.',
      'Die Benutzeroberfläche ist eine einzige Telegram-Nachricht. Alles andere passiert im Hintergrund.',
    ]},
    { type: 'image', index: 2, eyebrow: 'Bild 02', label: 'Der Einstiegspunkt', caption: '„So viel zur Benutzeroberfläche. Keine separate App, keine Einarbeitung."', alt: 'Smartphone-Bildschirm mit der Telegram-Unterhaltung' },
    { type: 'heading', title: 'Ein echtes Beispiel von heute', subtitle: 'Vier Worte, und eine fertige Strategie' },
    { type: 'paragraphs', items: [
      'Kein erfundener Fall. Heute Nachmittag habe ich eine Sprachnachricht geschickt, die nur lautete: „Mach du das." Das System hat die Sprachnachricht transkribiert, verstanden, dass es sich um eine Entscheidungsübergabe handelt, und nicht nachgefragt, sondern angefangen zu arbeiten.',
    ]},
    { type: 'quote', entries: [
      { speaker: 'Ich, per Sprachnachricht', text: '„Mach du das."' },
      { speaker: 'Brunella', text: 'Alles klar, ich übernehme. Deine Sprachnachricht habe ich transkribiert. Den ersten Schritt der Strategie habe ich fertiggestellt, versandbereit …' },
    ]},
    { type: 'paragraphs', items: [
      'Was zwischen den beiden Nachrichten geschah: Sie hat alle dreiundzwanzig Projektnotizen in meiner Wissensdatenbank durchgelesen, die acht Kundenprojekte verglichen, den tatsächlichen Stand meiner fünf eigenen Produkte geprüft, ein gemeinsames Muster erkannt, das mir selbst nicht aufgefallen war, daraus ein gegliedertes, gut lesbares Dokument geschrieben und dazu auch gleich die Entwürfe der passenden Kunden-E-Mails vorbereitet.',
      'Eine Sache hat sie dabei nicht getan: nichts verschickt. Die E-Mails wurden vorbereitet, aber das Versenden hat sie mir überlassen, weil das ein nicht rückgängig zu machender Schritt ist. Dazu später mehr.',
    ]},
    { type: 'image', index: 3, eyebrow: 'Bild 03', label: 'Das Beispiel', caption: '„Vier Worte als Eingabe, ein fertiges Dokument als Ergebnis."', alt: 'Screenshot der Telegram-Unterhaltung, in der auf eine kurze Nachricht eine lange, gegliederte Antwort folgt' },
    { type: 'heading', title: 'Das Team', subtitle: 'Acht Spezialisten, jeder mit eigenem Aufgabenbereich' },
    { type: 'paragraphs', items: [
      'Die Mitglieder des Teams laufen getrennt, mit eigener Persönlichkeit und eigenem Gedächtnis. Es sind keine Kopien desselben Programms: Jeder hat ein anderes Fachgebiet, und manche laufen sogar auf einer anderen KI-Engine, weil die für diese Aufgabe besser geeignet ist.',
    ]},
    { type: 'list', items: [
      { name: 'Brunella', role: 'Die Koordinatorin. Sie spricht mit mir, verteilt die Arbeit und verantwortet das Endergebnis.' },
      { name: 'Kenshin', role: 'Softwareentwicklung: Code schreiben, Fehler beheben, Architektur, Versionsverwaltung.' },
      { name: 'Lumen', role: 'Websites, Benutzeroberfläche und visuelle Identität. Bringt gemeinsam mit Kenshin Webprojekte vom Entwurf bis zum fertigen Code.' },
      { name: 'Aura', role: 'Marktforschung, Vergleichsanalysen, Recherche und Prüfung von Quellen.' },
      { name: 'Irisz', role: 'Datenanalyse, Reporting, Aufbereitung von Geschäfts- und Marketingzahlen.' },
      { name: 'Nyomozó (Detektiv)', role: 'Der Hüter des Gedächtnisses. Findet heraus, was wir vor drei Wochen entschieden haben und warum.' },
      { name: 'Zeph', role: 'Kundschafter: testet neue Werkzeuge und baut neue Fähigkeiten für das Team auf.' },
      { name: 'Agy & Pilot (Gehirn & Pilot)', role: 'Reserve-Engines. Fällt der primäre KI-Dienst aus, steht die Arbeit nicht still.' },
    ]},
    { type: 'paragraphs', items: [
      'Ist eine Aufgabe komplex, zerlegt die Koordinatorin sie und gibt die Teile an den jeweils zuständigen Spezialisten weiter. Die Spezialisten können sich auch gegenseitig Nachrichten schicken, sodass die Arbeit weitergeht, auch wenn ich mich gerade um etwas anderes kümmere.',
    ]},
    { type: 'image', index: 4, eyebrow: 'Bild 04', label: 'Das Team', caption: '„Das Team. Jeder läuft für sich, aber alle arbeiten am selben Ziel."', alt: 'Die Agenten-Liste im Dashboard, aus der hervorgeht, wer läuft und woran gerade gearbeitet wird' },
    { type: 'image', index: 5, eyebrow: 'Bild 05', label: 'Zusammenarbeit', caption: '„Kein einzelnes Programm. Ein Team, das miteinander spricht."', alt: 'Ein Nachrichtenaustausch zwischen Agenten, bei dem einer dem anderen eine Aufgabe übergibt' },
    { type: 'heading', title: 'Gedächtnis', subtitle: 'Nichts muss zweimal gesagt werden' },
    { type: 'paragraphs', items: [
      'Bei den meisten KI-Systemen beginnt jedes Gespräch bei null. Hier nicht. Das System verfügt über drei Arten von Gedächtnis, ungefähr so wie ein Mensch: was gerade jetzt wichtig ist, was eine dauerhafte Gewohnheit oder Einstellung ist, und was eine Lehre aus einem früheren Fehler ist.',
      'Taucht ein Thema auf, sucht das System auf zwei Arten gleichzeitig: nach wörtlicher Übereinstimmung und nach inhaltlicher Ähnlichkeit. Deshalb findet es eine Entscheidung von vor Monaten auch dann, wenn ich heute mit ganz anderen Worten danach frage.',
      'Zusätzlich wird wichtiges Wissen auch in für Menschen lesbaren Notizen festgehalten, die ich selbst durchsehen kann. Keine Blackbox: Ich kann jederzeit nachsehen, was das System über mich weiß und warum.',
    ]},
    { type: 'image', index: 6, eyebrow: 'Bild 06', label: 'Gedächtnis', caption: '„Drei Gedächtnisebenen, durchsuchbar und auch für Menschen lesbar."', alt: 'Die Speicheransicht bzw. der Beziehungsgraph im Dashboard' },
    { type: 'heading', title: 'Lernen', subtitle: 'Was einmal schwer war, ist beim zweiten Mal ein Rezept' },
    { type: 'paragraphs', items: [
      'Das ist vielleicht die ungewöhnlichste Eigenschaft dieses Systems. Wenn ein Agent etwas Komplexes erledigt oder auf einen Fehler stößt und ihn löst, schreibt er sich anschließend selbst ein Rezept: wann man es braucht, was die richtige Reihenfolge ist und welche Fallstricke gerade aufgetreten sind.',
      'Beim nächsten Mal fängt er nicht mehr bei null an. Das ist keine Theorie: Auch heute sind so zwei neue Rezepte entstanden. Eines davon hält fest, wo bei der Transkription einer Sprachnachricht Dateipfade genau ins Stocken geraten. Dieser Fehler passiert im Team kein zweites Mal.',
      'Die Rezepte lassen sich teilen: Was auf einem Rechner gelernt wurde, bekommen auch die anderen Installationen.',
    ]},
    { type: 'image', index: 7, eyebrow: 'Bild 07', label: 'Lernen', caption: '„Das System schreibt sich selbst auf, was es gelernt hat."', alt: 'Eine Skill-Datei bzw. die Liste der Fähigkeiten, mit den Abschnitten „Ablauf" und „Fallstricke"' },
    { type: 'heading', title: 'Aufgabenverwaltung', subtitle: 'Ein Board, das die Arbeit von selbst aufteilt' },
    { type: 'paragraphs', items: [
      'Aufgaben leben auf einem Board, wie es bei einem Team üblich ist. Der Unterschied: Eine große Aufgabe zerlegt das System selbst in kleinere Schritte und verteilt sie selbst an den passenden Spezialisten.',
      'Das Board meldet sich, wenn eine Karte zu lange an derselben Stelle liegt, und begrenzt, wie viele Dinge gleichzeitig laufen dürfen — denn parallel liegen gebliebene Halbfertigarbeit ist das Teuerste in einem Unternehmen.',
      'Und es gibt eine Regel, die mir wichtig ist. Kommt ein Agent nicht weiter und braucht meine Entscheidung, bleibt er nicht stillschweigend stehen. Er schreibt auf die Karte, genau was ich entscheiden muss, und weist die Karte mir zu, damit die Verantwortung sichtbar bleibt.',
    ]},
    { type: 'image', index: 8, eyebrow: 'Bild 08', label: 'Aufgaben-Board', caption: '„Das Board verwaltet nicht nur: Es zerlegt, verteilt und meldet sich, wenn etwas hängen bleibt."', alt: 'Das Kanban-Board mit Spalten und einigen Karten' },
    { type: 'heading', title: 'Nachtschicht', subtitle: 'Arbeitet auch, wenn niemand hinschaut' },
    { type: 'paragraphs', items: [
      'In regelmäßigen Abständen schaut sich das System von selbst um: Gibt es eine unbeantwortete Nachricht, ist etwas passiert, das man sich merken sollte, hat es etwas Neues gelernt, das ein Rezept verdient.',
      'Die wichtigste Regel dabei ist Stille. Gibt es nichts Wesentliches zu berichten, meldet sich das System nicht. Ein Assistent, der sich stündlich meldet, um zu sagen „nichts Neues", wird nach wenigen Tagen unerträglich. Dieser hier schreibt nur, wenn es wirklich einen Grund gibt.',
      'Daneben laufen auch geplante Aufgaben: tägliche und wöchentliche Zyklen, die wir einmal einrichten und die danach von selbst laufen.',
    ]},
    { type: 'image', index: 9, eyebrow: 'Bild 09', label: 'Zeitplanung', caption: '„Tägliche und wöchentliche Zyklen, ohne Aufsicht."', alt: 'Die Liste der geplanten Aufgaben mit ihrer Zeitplanung' },
    { type: 'heading', title: 'Kontrolle', subtitle: 'Autonomie hat Abstufungen' },
    { type: 'paragraphs', items: [
      'Das ist der Teil, den die meisten zu Recht fragen: Was passiert, wenn eine KI selbstständig arbeitet und einen Fehler macht?',
      'Die Antwort: Jeder Aktionstyp im System hat eine eigene Autonomiestufe, die ich selbst festlege. Auf der ersten Stufe meldet das System nur, was es tun würde. Auf der zweiten holt es die Erlaubnis ein und wartet auf meine Antwort. Auf der dritten erledigt es die Aufgabe und meldet sich danach.',
      'Was nicht rückgängig zu machen ist oder nach außen wirkt, braucht immer eine Freigabe. E-Mails versenden, Daten löschen, Zahlungen auslösen, öffentlich veröffentlichen: Das System bereitet all das vor, drückt aber nicht selbst den Knopf für mich. Das ist keine Einschränkung, sondern genau das, was das System vertrauensvoll nutzbar macht.',
    ]},
    { type: 'image', index: 10, eyebrow: 'Bild 10', label: 'Freigabe', caption: '„Was nicht rückgängig zu machen ist, bekommt immer ein menschliches Ja."', alt: 'Die Token-Monitor-Ansicht: Token- und Kostenverbrauch pro Agent, mit Zeitverlaufsdiagramm' },
    { type: 'heading', title: 'Zugriff', subtitle: 'Nicht von der Welt abgeschnitten' },
    { type: 'paragraphs', items: [
      'Ein Assistent ist nur so gut wie die Werkzeuge, die er tatsächlich erreicht. Brunella lässt sich mit E-Mail, Kalender, Cloud-Speicher, Code-Repository, Notizsystem, Browser und Automatisierungs-Engine verbinden — und erledigt darüber echte Arbeit, statt nur darüber zu reden.',
      'Ich schalte die Zugriffe einzeln frei und kann sie jederzeit widerrufen. Passwörter und Schlüssel liegen in einem verschlüsselten Speicher, nicht in der Unterhaltung.',
    ]},
    { type: 'image', index: 11, eyebrow: 'Bild 11', label: 'Verbindungen', caption: '„E-Mail, Kalender, Speicher, Code-Repository, Automatisierung. Einzeln freigeschaltet."', alt: 'Die Liste der verbundenen Dienste bzw. die Einstellungsoberfläche' },
    { type: 'heading', title: 'Mehrere Systeme', subtitle: 'Zwei Teams können bei Bedarf zusammenfinden' },
    { type: 'paragraphs', items: [
      'Hat jemand ein eigenes Brunella-System, lassen sich beide verbinden. Mein Team kann dann einen Spezialisten der anderen Seite um Rat fragen, und umgekehrt, ohne dass eine der beiden Seiten der anderen Zugriff auf die eigenen Daten gibt.',
      'Die Grenze ist strikt: Es überquert nur der Text der Aufgabe — nie ein Geheimnis, ein Passwort oder personenbezogene Daten. Das System behandelt eine von der anderen Seite eingehende Anfrage standardmäßig als Daten, nicht als Befehl.',
    ]},
    { type: 'image', index: 12, eyebrow: 'Bild 12', label: 'Verbund', caption: '„Getrennte Systeme, gemeinsame Arbeit, ohne gemeinsame Daten."', alt: 'Die Vault-Ansicht: die Liste der verschlüsselt gespeicherten Schlüssel und API-Token' },
    { type: 'heading', title: 'In Zahlen', subtitle: 'Wo die Beta gerade steht' },
    { type: 'stats', items: [
      { value: '8', label: 'Spezialisten-Agenten im Team' },
      { value: '24', label: 'gelernte, wiederverwendbare Rezepte' },
      { value: '14', label: 'anbindbare Dienste' },
      { value: '12', label: 'selbstständig laufende geplante Zyklen' },
    ], note: 'Das System läuft auf meinem eigenen Rechner, nicht auf dem Server eines externen Anbieters. Die Gespräche, die Notizen und die Kundendaten bleiben bei mir.' },
    { type: 'image', index: 13, eyebrow: 'Bild 13', label: 'Schlussbild', caption: '„Brunella System, Beta. Wird aufgebaut, lernt, arbeitet."', alt: 'Das Dashboard in einem lebendigen, arbeitsreichen Moment: laufende Agenten, sich bewegende Aufgaben' },
    { type: 'closing', title: 'Was ehrlich gesagt werden muss', body: 'Das ist eine Beta. Sie verändert sich von Tag zu Tag, und nicht jeder Teil ist gleich ausgereift. Ich verspreche nicht, dass sie fehlerfrei ist, sondern dass sie es nicht verschweigt, wenn etwas nicht geklappt hat, und dass bei nicht rückgängig zu machenden Schritten immer ein Mensch entscheidet. Nach den Erfahrungen der letzten Monate ist das System nicht deshalb nützlich, weil es alles weiß, sondern weil es sich erinnert, dazulernt und nicht aufhört, wenn ich den Laptop zuklappe.' },
  ],
};

export const brunellaBetaImageSrcs = Array.from({ length: 13 }, (_, i) =>
  `/images/brunella-system-beta/${String(i + 1).padStart(2, '0')}.png`
);
